### ISSUE TITLE
how can i train my model with mask picture/video ?

### ISSUE THREAD

**Issue by 565ee** [baaivision/EVA#2] opened 2022-11-20 18:21 UTC
how can i train my model with mask picture/video ?

**Comment by Yuxin-CV** [comment] 2022-11-21 01:24
Hi, what do you mean by "mask picture/video"?

**Comment by Yuxin-CV** [comment] 2022-11-27 16:18
The issue is no longer active, as such I'm closing this. Feel free to ask if you have further questions.

**Closed by Yuxin-CV** 2022-11-27 16:18 UTC
