### ISSUE TITLE
how many types in the pre-trained model? as coco?

### ISSUE THREAD

**Issue by MollyHoo** [baaivision/EVA#37] opened 2023-02-09 09:35 UTC
how many types in the pre-trained model? as coco?

**Comment by Yuxin-CV** [comment] 2023-02-15 05:17
Hi, if you are interested in the detection part, please read the [README](https://github.com/baaivision/EVA/blob/master/det/README.md) first.

**Comment by Yuxin-CV** [comment] 2023-02-23 03:58
The issue is no longer active, as such I'm closing this. Feel free to ask if you have further questions.

**Closed by Yuxin-CV** 2023-02-23 03:58 UTC
